name: Check Links

on:
  schedule:
    - cron: '0 13 * * 1'
  workflow_dispatch: {}
  pull_request:
    paths:
      - 'popup.html'

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm run check-links
